accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from .views import *
from .import views 




app_name ="accounts"

urlpatterns = [
  
   
     path('register/' ,CustomerRegistrationView.as_view(),name='register'),
      path('training/' ,views.training,name='training'),
       path('login/' ,views.loginPage,name='login'),
         path('logout/' ,views.logoutPage,name='logout'),
        path('company/' ,CompanyRegistrationView.as_view(),name='company'),   
         
         
     
          path('reset_password/' ,auth_views.PasswordResetView.as_view(),name='reset_password'),
        path('reset_password_sent/' ,auth_views.PasswordResetDoneView.as_view(),name='password_reset_done'),
        path('reset/<uidb64>/<token>/' ,auth_views.PasswordResetConfirmView.as_view(template_name='account/password_reset_confirm.html'),name='password_reset_confirm'),
        path('reset_password_complete/' ,auth_views.PasswordResetCompleteView.as_view(),name='reset_password_complete'),



    
]

product/urls.py
from django.urls import path

from django.contrib.sitemaps.views import sitemap
from product.sitemaps import ProductSitemap ,CourseSitemap 

from .views import *
from .import views 


sitemaps={
    'product':CourseSitemap,
    'course':ProductSitemap,
}

app_name ="product"

urlpatterns = [
  
    path('' ,views.home,name='home'),
    path('about/' ,views.about_us,name='about'),
    path('services/' ,views.services,name='services'),
    path('blog/' ,views.blog,name='blog'),
    path('recruitment/' ,views.recruitment,name='recruitment'),
    path('contact/' ,views.contactUs,name='contact'),

     path('web/' ,views.webDevelopment,name='web'),

     path('support/' ,views.supportUs,name='support'),
     path('mobile/', views.mobileApp,name='mobile'),
    path('digital/', views.digital,name='digital'),

    path('machine/', views.machine_learning,name='machine'),
     path('game/', views.game,name='game'),
      path('database/', views.database,name='database'),

      path('train/' ,views.train,name='train'),
      path('course_detail/<int:pk>/', views.detail,name='course_detail'),
      path('advanced_course_detail/<int:pk>/', views.readmore,name='advanced_course_detail'),  
      
      #seo path

      #path('sitemap.xml', sitemap, {'sitemaps':sitemaps}), 
      path('sitemap.xml', sitemap, {'sitemaps':sitemaps}),   
      
]

realmind/urls.py
from django.contrib import admin

from django.urls import path ,include
from django.conf import settings
from django.conf.urls.static import static




urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('product.urls')),
     path('accounts/' , include('accounts.urls')),
     path('accounts/', include('django.contrib.auth.urls')),
    
]


urlpatterns = urlpatterns + static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT)

templates/contact.html
{% extends 'index.html' %}
{% load static %}  
{% block content %} 

{% load crispy_forms_tags %} 

<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<style>
    .caro{
    display: none;
}
  .features{
        display: none;
    }
    .about{
        display: none;
    }
    .realmind{
      display: none;
  }
  .banner{
     display: none;
   }
   .contact .content {
    /* max-width: 800px; */
    /*text-align: center;
    width: 100%;*/
}
/*.contact .container {
    width: 100%;
}
.contact .container {
    width: 100%;
}
.contact .container .contactInfo {
    width: 50%;
    display: flex;
    flex-direction: column;
    margin-left: 20px;
}
.contact .container .contactInfo .box .text{
    display: flex;
    margin-left: 10px;
    font-size: 16px;
    color: #333;
    flex-direction: column;
    font-weight: 400;
    font-family: "Roboto", sans-serif;
}*/

</style>


<section class="contact">
    
	<div class="content">
		<h2>Contact Us</h2>
		<p>Contact us today for a new experience with technology </p>
	</div>
	<div class="container">
		<div class="contactInfo">
			<div class="box">
				<div class="icon">
                    <i class="fa fa-address-card"></i>
                </div>
				<div class="text">
					<h3>Address</h3>
					<p>7/12 Rumens road <br> Ikoyi , Lagos</p>
				</div>
			</div>
			<div class="box">
				<div class="icon">
                    <i class="fa fa-phone-square-alt"></i>
                </div>
				<div class="text">
					<h3>Phone</h3>
					<p>+2348079385255 </p>
					<p>Whatsapp +2348079385255 </p>
				</div>
                <!--<div class="text">
					<h3>Phone</h3>
					<p>08177206739 </p>
					<p>Whatsapp  :08177206739 </p>
				</div>-->
			</div>
			<div class="box">
				<div class="icon">
                    <i class="fa fa-envelope-square"></i>
                </div>
				<div class="text">
					<h3>Email</h3>
					<p>realmindt@gmail.com</p>
				</div>
			</div>
		
		</div>
        <div class="contactForm">
            <form action="{% url 'product:contact' %}" method="POST">
                <h2>Send Us A  Message  - {{ message_name }}</h2>
                {% csrf_token %}
                <div class="inputBox">
                    <input type="text" name="message-name" placeholder="Full name" required>
                    <!--<span>Full Name</span>-->
                </div>
                <div class="inputBox">
                    <input type="text" name="message-phone" placeholder="Phone Number" required>
                   <!--- <span>Phone</span>-->
                </div>
                <div class="inputBox">
                    <input type="text" name="message-email" placeholder="Email" required>
                    <!--<span>Email</span>-->
                </div>
                <div class="inputBox">
                    <textarea name="message" placeholder="Type your message here" id="" cols="30" rows="10"></textarea>
                    <!--<span>Type your message</span>-->
                </div>
                <div class="inputBox">
                    <input type="submit" name="" value="Send">
                   
                </div>
            </form>

        </div>
	</div>
</section>
 <!--font awsome-->
 















{% endblock %}

templates/footer.html
<footer class="footer">
    <div class="container">
        <div class="row">
            <div class="footer-col">
                <h4>company</h4>
                <ul>
                    

                   <li><a href="#"> 7/12 Rumens road ikoyi <br>lagos <br>
                    <strong>Phone:</strong> +2348079385255</a></li>
                  
                </ul>
            </div>
            <div class="footer-col">
                <h4>Useful links</h4>


                <ul>
                    <li><a href="{% url 'product:home'%}"> Home </a><li>
                    <li><a href="{% url 'product:about'%}"> About us </a></li>
                    <li><a href="{% url 'product:services'%}"> Services </a></li>
                    <li><a href="{% url 'product:recruitment'%}"> Recruitment </a></li>
                    <li><a href="{% url 'product:train'%}"> Training </a></li>
                </ul>
              
            </div>
            <div class="footer-col">
                <h4>Our services</h4>
                <ul>
                    <li><a href="{% url 'product:mobile'%}"> Mobile app </a></li>
                    <li><a href="{% url 'product:web'%}"> web Development </a></li>
                    <li><a href="{% url 'product:train'%}"> Product management</li>
                    <li><a href="{% url 'product:digital'%}"> Digital marketing </a></li>
                    <li><a href="{% url 'product:train'%}"> Graphic Design </a></li>
                </ul>
              
            </div>
            <div class="footer-col">
                <h4>Contact Us</h4>
                <ul>
                    <li><a href="#">+2348079385255 </a></li>
                    <li><a href="#"> +2348098800103</a></li>
                    <li><a href="#" style="text-transform: lowercase;">realmindt@gmail.com</a></li>
                    
                </ul>
              
            </div>
            <div class="footer-col">
                <h4>follow us</h4>
                <div class="social-links">
                    <a href=""><i class="fa fa-facebook-f"></i></a>
                    <a href=""><i class="fa fa-twitter"></i></a>
                    <a href=""><i class="fa fa-instagram"></i></a>
                    <a href=""><i class="fa fa-linkedin-in"></i></a>
                </div>
            </div>
        </div>
    </div>

</footer>

templates/home.html
{% extends 'index.html' %}
 {% load static %}
{% block content %}


<style>
	@media (max-width: 930px){
		.carousel{
  margin-top: 20px;
  height: 65vh;
  padding-left: 0px;
  padding-right: 0px;

}

@media (max-width:768) {
	.container .col-md-3 {
 
  width: 45%;
  padding: 20px;
}
@media (max-width:600) {
	.container .col-md-3 {
    
    width: 40% !important;
    padding: 20px;
}
}
	
}
	}
</style>
<div class="caro">

	<section class="container">
		<div id="carouselExampleDark" class="carousel carousel-dark slide" data-bs-ride="carousel">
			<div class="carousel-indicators">
			  <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
			  <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="1" aria-label="Slide 2"></button>
			  <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="2" aria-label="Slide 3"></button>
			</div>
			<div class="carousel-inner">
			  <div class="carousel-item active animate__animated animate__rotateIn animation-delay-0s" >
				<img src="{% static 'images/computer9.jpg' %}" class="d-block w-100" alt="...">
				<div class="carousel-caption d-none d-md-block">
				  <!--<h5 >First slide label</h5>
				  <p>Some representative placeholder content for the first slide.</p>-->
				</div>
			  </div>
			  <div class="carousel-item animate__animated animate__rotateInDownLeft animation-delay-3s" data-bs-interval="2000">
				<img src="{% static 'images/teacher2.jpg' %}" class="d-block w-100" alt="...">
				<div class="carousel-caption d-none d-md-block">
				  <!--<h5>Second slide label</h5>
				  <p>Some representative placeholder content for the second slide.</p>-->
				</div>
			  </div>
			  <div class="carousel-item animate__animated animate__backInRight animation-delay-6s">
				<img src="{% static 'images/ai/ai3.jpg' %}" class="d-block w-100" alt="...">
				<div class="carousel-caption d-none d-md-block">
				  <!--<h5>Third slide label</h5>
				  <p>Some representative placeholder content for the third slide.</p>-->
				</div>
			  </div>
			  <div class="carousel-item animate__animated animate__bounceInDown animation-delay-9s">
				<img src="{% static 'images/code1.jpg' %}" class="d-block w-100" alt="...">
				<div class="carousel-caption d-none d-md-block">
				  <!--<h5 style="color: white; position: absolute; top: -50;">Third slide label</h5>
				  <p style="color: white;">Some representative placeholder content for the third slide.</p>-->
				</div>
			  </div>
			</div>
			<button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="prev">
			  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
			  <span class="visually-hidden">Previous</span>
			</button>
			<button class="carousel-control-next" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="next">
			  <span class="carousel-control-next-icon" aria-hidden="true"></span>
			  <span class="visually-hidden">Next</span>
			</button>
		  </div>
	
	 </section>
</div>



<section class="features">
	<div class="container">
		<div class="row">
			<div class="col-lg-12">
				<div class="feature-block d-lg-flex">
					<div class="feature-item mb-5 mb-lg-0">
						<div class="feature-icon mb-4">
						</div>
						<!--<span>Online Services</span>-->
						<h4 class="mb-3">Pysical classroom</h4>
						<p class="mb-4">100% practical </p>
						<p class="mb-4">Condusive learning environment </p>
						<p class="mb-4">One on one tutorial </p>
						<p class="mb-4">Move from zero to professional software developer </p>
						
						<a href="{% url 'product:contact' %}" class="btn btn-main btn-round-full">Make a appoinment</a>
					</div>

					<div class="feature-item mb-5 mb-lg-0">
						<div class="feature-icon mb-4">
						
						</div>
						<!--<span>Online Services</span>-->
						<h4 class="mb-3">Online Services</h4>
						<p class="mb-4">100% practical </p>
						<p class="mb-4">Flexible time </p>
						<p class="mb-4">24/7 support system</p>
						<p class="mb-4">Move from zero to professional software developer </p>
						
						
						<a href="{% url 'product:contact' %}" class="btn btn-main btn-round-full">Make a appoinment</a>
					</div>
					
				
					<div class="feature-item mb-5 mb-lg-0">
						<div class="feature-icon mb-4">
							<i class="icofont-support"></i>
						</div>
						<h4 class="mb-3">Working Hours</h4>
						<ul class="w-hours list-unstyled">
		                    <li class="d-flex justify-content-between">Mon - Wed : <span>9:00 - 17:00</span></li>
		                    <li class="d-flex justify-content-between">Thu - Fri : <span>10:00 - 17:00</span></li>
		                    <li class="d-flex justify-content-between">Sat  : <span>10:00 - 17:00</span></li>

		                    <li class="d-flex justify-content-between">sun : <span>:On appointment</span></li>

		                    </ul>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

<!--products here-->


<div class="row justify-content-center realmind" style="margin-top: 50px;">
	<div class="col-lg-6">
		<div class="section-title">
			<h2>Important Benefit of learning from us</h2>
		</div>
		<div class="desc">
		<ol>
			<li class="animate__animated animate__backInLeft animation-delay-1s"><h4>100% One on one practical tutorial </h4></li>
			<li class="animate__animated animate__backInRight animation-delay-2s" style="animation-delay: 2s;"><h4>We assume you dont know anything so we teach you from scratch to professional level</h4></li>
		    <li class="animate__animated animate__rotateIn animation-delay-1s h2" style="animation-delay: 3s;"><h4>Deployment of your projects online</h4></li>
			<li class="animate__animated animate__rotateIn animation-delay-1s h2" style="animation-delay: 4s;"><h4>Two projects before you finish your program with us</h4></li>
			<li class="animate__animated animate__rotateInDownLeft animation-delay" style="animation-delay: 5s;"><h4>Teach you how you can save your projects so intending employers can see your work</h4></li>
			<li class="animate__animated animate__backInLeft animation-delay" style="animation-delay: 6s;"><h4>Teach you how you can apply for foreign companies</h4></li>
			<li class="animate__animated animate__backInRight animation-delay" style="animation-delay: 7s;"><h4>Help you source for jobs online</h4></li>
		</ol>
		</div>

	</div>

	<div class="col-lg-6">
		<h2 class="fact">Current Fact</h2>
		<div class="section-right animate__animated animate__bounceInDown animation-delay-3s">
			
		
		<p>There's no question that software programming is a hot career right now. A recent research by The U.S. Bureau of Labor Statistics projects 21 percent growth for programming jobs from 2018 to 2028, which is more than four times the average for all occupations. What’s more, the median annual pay for a software programmer is about $106,000, which nearly three times the median pay for all workers around the world .</p>
	
	</div>
</div>
</div>
















<div class="prod">
	<div class="container">
		<h1>Some high in-demand skills around the globe</h1>
		<div class="row my-5">
			{% for course in courses %}

			<div class="col-md-3 my-4">
		   <a href="{% url 'product:course_detail' course.pk %}">
		  
				<img  src="{{ course.img.url }}" alt="" class="w-100">
				<h4 class="my-">{{ course.name }}</h4>
					<h3 class="average">Average salary:<span class="price"> ${{course.pay}}</span></3>
				 <!--<a href="" class="opt">view options ></a>-->
				
				<p  class="describe">{{course.desc |truncatewords:30}}</p>
					
		   </a>
			</div>
			{% endfor %}
		
			</div>
		</div>
	</div>


<section class="section service gray-bg">
	<div class="container">
		<div class="row">
			<h3>Other courses</h3>
			{% for course in product %}
			<div class="col-lg-4 col-md-6 col-sm-6">
				<div class="service-item mb-4">
					<div class="icon d-flex align-items-center">
						<i class="{{course.icon}}"></i>
						
						<h4 class="mt-3 mb-3">{{ course.name }}</h4>
					</div>

					<div class="content">
						<p class="mb-4">{{course.desc  |truncatewords:35}} <a href="{% url 'product:advanced_course_detail' course.pk %}" class="read-more">Read more</a></p>
					</div>
				</div>
			</div>
			{% endfor %}


		</div>
	</div>
</section>






<section class="section about">
	<div class="container">
		<div class="row align-items-center">
			<div class="col-lg-4 col-sm-6">
				<div class="about-img">
					<img src="{% static 'images/webapp3.png' %}" alt="" class="img-fluid">
					<img src="{% static 'images/mobile4.jpg' %}" alt="" class="img-fluid mt-4">
				</div>
			</div>
			<div class="col-lg-4 col-sm-6">
				<div class="about-img mt-4 mt-lg-0">
					<img src="{% static 'images/mobile1.jpg' %}" alt="" height="1000" class="img-fluid">
				</div>
			</div>
			<div class="col-lg-4">
				<div class="about-content pl-4 mt-4 mt-lg-0">
					<h2 class="title-color"><br> develop yourself and start providing your service to the world</h2>
					<p class="mt-4 mb-5">We provide best with the best tutors</p>

					<a href="{% url 'product:services' %}" class="btn btn-main-2 btn-round-full btn-icon">Services<i class="icofont-simple-right ml-3"></i></a>
				</div>
			</div>
		</div>
	</div>
</section>







{% endblock %}

templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="zxx">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
 
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>Realmind Tech</title>

  <!-- Favicon -->
  <!--<link rel="shortcut icon" type="image/x-icon" href="{% static 'images/favicon.ico' %}" />-->

<!--bootsrap link-->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

 
  
  
  <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    
    <!--animation link-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"/>




	 
  

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Noto+Sans+Display:ital,wght@0,100;0,300;0,400;0,500;0,600;0,900;1,200;1,300;1,400;1,500;1,600;1,700;1,800&family=Oswald:wght@200;300;400&family=Poppins:ital,wght@0,200;0,500;1,200;1,600&display=swap" rel="stylesheet">
<!--font awesome-->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.15.4/css/fontawesome.min.css">


 <!--font awesome-->
 <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.15.4/css/fontawesome.min.css">


<link rel="stylesheet" href="{% static 'styles/style.css' %}">
</head>

<body id="top">


<style>



</style>
   
	<!--<a href="{% url 'product:home' %}" class="brandy" style="color:#223a66; font-size: 30px;font-family: Georgia, 'Times New Roman';"><span><img src="/static/images/brand/r1.png"  style="width: 40px;height: 80px; padding-left:20px" alt="">Mind</span><span style="color: #e12454;">Tech</span></a>-->
		
<header>
	<div class="header-top-bar" id="header-top">
		<div class="container">
			<div class="row align-items-center">
				<div class="col-lg-6">
					<ul class="top-bar-info list-inline-item pl-0 mb-0">
						<li class="list-inline-item"><a href="mailto:realmind_t@gmail.com"><i class="icofont-support-faq mr-2"></i>realmindt@gmail.com</a></li>
						<li class="list-inline-item"><i class="icofont-location-pin mr-2"></i>7/12 Rumens Road, Ikoyi, Lagos </li>
					</ul>
				</div>
				<div class="col-lg-6">
					<div class="text-lg-right top-right-bar mt-2 mt-lg-0">
						<a href="tel:+2348079385255" >
							<span>Call Now : </span>
							<span class="h4">+2348079385255 | +2348098800103</span>
						</a>
					</div>
				</div>
			</div>
		</div>
	</div>



	<nav class="navbar navbar-expand-lg navigation" id="navbar">
		<div class="container">
		 	 <a class="navbar-brand" href="{% url 'product:home' %}">
				 <a href="{% url 'product:home' %}" class="brandy" style="color:#223a66; font-size: 30px;font-family: Georgia, 'Times New Roman'"><span><img src="/static/images/brand/r1.png"  style="width: 40px;height: 80px; padding-left:20px" alt="">Mind</span><span style="color: #e12454;">Tech</span></a>
				  
			  </a>

	     <input type="checkbox" id="checkbox_toggle" />
	      <label for="checkbox_toggle" class="hamburger" onclick="checkToggle()">&#9776;</label>
		  

		  <div class="collapse navbar-collapse" id="navbarmain">
			<ul class="navbar-nav ml-auto" id="navbar-nav">
			  <li class="nav-item active">
				<a class="nav-link" href="{% url 'product:home' %}">Home</a>
			  </li>
			   <li class="nav-item"><a class="nav-link" href="{% url 'product:about' %}">About</a></li>
			   
			   <li class="nav-item"><a class="nav-link" href="{% url 'product:services' %}">Services</a></li>

			
				  <li class="nav-item"><a class="nav-link" href="{% url 'product:recruitment' %}">Recruitment</a></li>
			   <li class="nav-item"><a class="nav-link" href="{% url 'product:contact' %}">Contact</a></li>
		
			   <li class="nav-item"><a class="nav-link" href="{% url 'accounts:training' %}">Training</a></li>

			   <li class="nav-item"><a class="nav-link" href="{% url 'product:support' %}">Support</a></li>
			 {% if user.is_authenticated %}
			 <li class="nav-item"><a class="nav-link" href="{% url 'accounts:logout' %}">logout</a></li>
			 {% else %}

			 <!--<li class="nav-item"><a class="nav-link" href="{% url 'accounts:register' %}">register</a></li>-->
			 <li class="nav-item"><a class="nav-link" href="{% url 'accounts:login' %}">login</a></li>
			 {% endif%}

			</ul>
		  </div>
		</div>
	</nav>
</header>



<div class="content" id="content">
	{% block content %}
	{% endblock %}
</div>




<script>
	function myFunction() {
  var x = document.getElementById("myTopnav");
  if (x.className === "topnav") {
    x.className += " responsive";
  } else {
    x.className = "topnav";
  }
}
</script>


{% include 'footer.html' %}



    <!-- 
    Essential Scripts
    =====================================-->



 


 <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>


  <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>

  

<script src="https://use.fontawesome.com/e503c766fc.js"></script>
    

    <!-- Google Map -->
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAkeLMlsiwzp6b3Gnaxd86lvakimwGA6UA&callback=initMap"></script>    
    
 
	<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>






<!-- Include js plugin -->


<script src="{% static 'js/script.js' %}"></script>

  </body>
  </html>
   

templates/recruitment.html
{% extends 'index.html' %}
 {% load static %}
{% block content %}


<style>
   .caro{
    display: none;
}
    .features{
        display: none;
    }
    .about{
        display: none;
    }
    .realmind{
      display: none;
  }
  .banner{
     display: none;
   }
    .feature{
        margin-top: 70px;
        margin-bottom: 150px;
       
       
        font-size: 22px;
        font-weight: 500;
        font-family: "Roboto", sans-serif;

        align-items: center;
        margin-right: 50px;
     
     
       
    }
    .feature-block{
        align-items: center;
        width: 100%
    }
    .feature-item{
        width: 1200px;
    }
   
    .feature-item{
        width: 900px;
    }
    .mb-3{
        text-align: center;
        margin-bottom: 30px;
    }

  
  
  /*p{
      font-size: 35px;
      font-family: "Roboto", sans-serif;
      color: #000;
  }*/
 

</style>





<section class="feature">
    <h4 class="mb-3">Developers' Recriutment </h4>
	<div class="container">
      
		<div class="row">
			<div class="col-lg-12">
				<div class="feature-block">
				

					<div class="feature-item">
						
						<!--<span>Online Services</span>-->
					
                   
                       <p class="mb-4" style="font-size: 20px;">Looking for softwae developers? Look no futher! <br> Realmind technology has a pool of dedicted and smart developers who are excellent in the  field and can turn your ideas into real products. </p>
                        <p class="mb-4" style="font-size: 20px;">Realmind Technology recruitment agency  provides a central platform to automate the candidate search, competency and hiring process. We have the best brains for any software project.
                        </p>
                        <p class="mb-4" style="font-size: 20px;">Recruiting competent developers for your software project is easier with Realmind technoloy.</p>
                         <!--<p>
                            Recruitment agency software is unique because it serves organizations exclusively focused on the sourcing and hiring process. In contrast, other recruiting software usually serves HR departments that handle recruiting in addition to other HR functions within a business. Staffing agency software, which focuses on building a pool of qualified talent to provide on-demand and temporary workers to companies, is closely related to recruitment agency software.
                            </p>
                            <p>Recruitment agency software offers suites for recruitment marketing, sourcing, applicant tracking, candidate relationship management, screening, assessment, interviewing, offering, hiring, onboarding, and analytics for recruiter performance and hiring trends.
                            </p>
                            <p>AI-powered sourcing tools scan job boards and social media, capture information, create candidate profiles, and rank them. Candidate relationship management features improve the candidate experience, leaving applicants more likely to accept employment offers, and create an environment where they would be more inclined to consider future opportunities. The sourcing and ongoing relationship management functions are particularly crucial for recruitment agencies, who often need standing pools of talent to source from.
                            </p>
                            <p>Screening tools collect documents to validate identities and enable background checks. Built-in assessment tools test applicant skills within the recruitment platform
                            </p>-->
                            <a type="button" class="btn btn-danger" href="{% url 'product:contact' %}">Contact Us</a>

					</div>
   	
                  		</div>
                          
                          
			</div>
            
		</div>
        
	</div>
   </section>

{% endblock %}